### ISSUE TITLE
Environment variables in run function

### ISSUE THREAD

**Issue by giggsoff** [itmo-eve/eveadm#1]
Please add environment variables as an argument in run function. This feature is required when transferring parameters to the rkt module.
As an example, for command of the following form:
```console
STAGE1_XL_OPTS=-p STAGE1_SEED_XL_CFG=xenCfgFilename rkt --dir=<RKT_DATA_DIR> --insecure-options=image run <SHA> --stage1-path=/usr/sbin/stage1-xen.aci --uuid-file-save=uuid_file --set-env=ENV-KEY=env-value
```
we need to pass:
```console
STAGE1_XL_OPTS=-p STAGE1_SEED_XL_CFG=xenCfgFilename
```

**Comment by sadov** [comment]
OK -- done: [commit fb36ef8](https://github.com/itmo-eve/eveadm/commit/fb36ef88f43586813b1e598133d0dd16df5633b0)

**Comment by giggsoff** [comment]
It works, thanks
