### ISSUE TITLE
Return retcode, stdout and stderr from run/rune

### ISSUE THREAD

**Issue by giggsoff** [itmo-eve/eveadm#3]
It is necessary to add stdout, stderr and a return code as return values ​​in run / rune functions. Since error handling and standard output should be performed on the side of functions executed through cobra.

**Comment by sadov** [comment]
Return values are added. Please check this modification.

**Comment by giggsoff** [comment]
Please fix line [fmt.Println("Timeout:", Timeout)](https://github.com/itmo-eve/eveadm/blob/ce8cdc745146f1d84b09c6e8631a8b1d40c8061e/cmd/root.go#L111) in root.go

**Comment by sadov** [comment]
Done.
